{% set name = "friendly" %}
{% set version = "0.5.36" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/friendly-{{ version }}.tar.gz
  sha256: 96526ef2c89c6456dd53c19e603f61c75afc5cadd5482b16a49ba169a854e635

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - appdirs
    - colorama
    - friendly-styles
    - friendly-traceback >=0.5.46
    - platformdirs
    - pygments >=2.6
    - python >=3.6
    - rich >=11

test:
  imports:
    - friendly
    - friendly.ipython_common
    - friendly.mu
    - friendly.theme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/friendly-traceback/friendly
  doc_url: https://friendly-traceback.github.io/docs/index.html
  summary: Friendlier tracebacks in any language.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
