{% set name = "friendly" %}
{% set version = "0.7.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/friendly-{{ version }}.tar.gz
  sha256: e826678896dafaa6c7a41b01820ee603bcb144c877f94c9e0addf0416b625ad1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - friendly = friendly.__main__:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - appdirs
    - colorama
    - friendly-styles
    - friendly-traceback >=0.5.51
    - platformdirs
    - pygments >=2.6
    - python >=3.6
    - rich >=11

test:
  imports:
    - friendly
  commands:
    - pip check
    - friendly --help
  requires:
    - pip

about:
  home: https://github.com/friendly-traceback/friendly
  doc_url: https://friendly-traceback.github.io/docs/index.html
  summary: Friendlier tracebacks in any language.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
