{% set name = "friendly" %}
{% set version = "0.7.20" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/friendly-{{ version }}.tar.gz
  sha256: 25ac8cb00a510c697c12af90c51a7ed6e6663a7fab7539f00b5f78c61a47e965

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - friendly = friendly.__main__:main

requirements:
  host:
    - pip
    - python >=3.6.1
  run:
    - friendly-styles
    - friendly-traceback >=0.7.43
    - platformdirs
    - pygments >=2.6
    - python >=3.6.1
    - rich >=11

test:
  imports:
    - friendly
  commands:
    - pip check
    - friendly --help
  requires:
    - pip

about:
  home: https://github.com/friendly-traceback/friendly
  doc_url: https://friendly-traceback.github.io/docs/index.html
  summary: Friendlier tracebacks in any language.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
