{% set name = "friendly" %}
{% set version = "0.7.21" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/friendly-{{ version }}.tar.gz
  sha256: 7417da84a9aff1a0a50c4bdc1dd594589abd3bf7333841c5313cf48616d5a9f2

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - friendly = friendly.__main__:main

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - friendly-styles
    - friendly-traceback >=0.7.43
    - platformdirs
    - pygments >=2.6
    - python >={{ python_min }}
    - rich >=11

test:
  imports:
    - friendly
  commands:
    - pip check
    - friendly --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/friendly-traceback/friendly
  doc_url: https://friendly-traceback.github.io/docs/index.html
  summary: Friendlier tracebacks in any language.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
