{% set name = "friendly" %}
{% set version = "0.5.27" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/friendly-{{ version }}.tar.gz
  sha256: 025c7a5f4b8af9d24c93bbbd14a1808e11367b68bd12b663842a921b7b230955

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - wheel
  run:
    - appdirs
    - colorama
    - friendly-styles
    - friendly-traceback >=0.4.104
    - pygments >=2.6
    - python >=3.6
    - rich >=10.13

test:
  imports:
    - friendly
#     - friendly.idle
    - friendly.ipython_common
    - friendly.mu
    - friendly.theme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/friendly-traceback/friendly
  doc_url: https://friendly-traceback.github.io/docs/index.html
  summary: Friendlier tracebacks in any language.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
