{% set name = "friendly" %}
{% set version = "0.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/friendly-{{ version }}.tar.gz
  sha256: 415731284ac24f7b6d9deeaa71ce6f5583c109beaefa1e9008012edfd22606ff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - appdirs
    - friendly-styles
    - friendly-traceback >=0.4.104
    - pygments >=2.6
    - python >=3.6
    - rich >=10.13

test:
  imports:
    - friendly
    - friendly.idle
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/friendly-traceback/friendly
  doc_url: https://friendly-traceback.github.io/docs/index.html
  summary: Friendlier tracebacks in any language.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
